### ISSUE TITLE
Compilation error:  FileLines.readTo() method type parameters

### ISSUE THREAD

**Issue by cheetah90** [yago-naga/yago3#1]
In [InfoboxExtractor](https://github.com/yago-naga/yago3/blob/master/src/main/java/fromWikipedia/InfoboxExtractor.java#L243), the `FileLines.readTo()`  takes multiple `String` as parameters but there is no such definitions in the FileLines class.  Ditto in Line 511 of TemporalInfoboxExtractor.java

**Comment by thomasrebele** [comment]
He should take [`readTo(Reader in, CharSequence... findMe)`](https://github.com/yago-naga/javatools/blob/595bc1fb4b84f63b5473d7914d1f09a4cef64a8f/src/main/java/javatools/filehandlers/FileLines.java#L171), line 171 in the most recent version of Javatools. How have you tried to compile it?
