### ISSUE TITLE
SubclassOf - Loop in Yago Taxonomy

### ISSUE THREAD

**Issue by AlexanderRassier** [yago-naga/yago3#3]
While working with the Taxonomy theme of Yago I discovered a SubclassOf - Loop that occured.
Here an example for the word 'banana':

<id_wJJCv2bY5e_owS_b!6mzcZmDD>	<wordnet_banana_112352287>	rdfs:subClassOf <wordnet_herb_112205694>	
<id_s4sT2Po9pU_owS_wx8ovn81Nd>	<wordnet_herb_107811416>	rdfs:subClassOf	<wordnet_flavorer_107809368>	
<id_wx8ovn81Nd_owS_F2sCKyy0LZ>	<wordnet_flavorer_107809368>	rdfs:subClassOf	<wordnet_ingredient_107809096>	
<id_dy5Q0XyPof_owS_PgQj?GFYnq>	<wordnet_ingredient_103570709>	rdfs:subClassOf	<wordnet_component_103081021>	
<id_X3onYh2zUU_owS_xvo7JAk1pw>	<wordnet_component_105868954>	rdfs:subClassOf	<wordnet_part_105867413>	
<id_VU?KozeXp!_owS_nW8x5wxL3!>	<wordnet_part_105256358>	rdfs:subClassOf	<wordnet_line_108593262>	
<id_OwcanXJ7ah_owS_?xOpUMAYqm>	<wordnet_line_108430568>	rdfs:subClassOf	<wordnet_formation_108426461>	
<id_?xOpUMAYqm_owS_HYEKsJd32Q>	<wordnet_formation_108426461>	rdfs:subClassOf	<wordnet_arrangement_107938773>	
<id_HYEKsJd32Q_owS_NITOoaqo!h>	<wordnet_arrangement_107938773>	rdfs:subClassOf	<wordnet_group_100031264>	
<id_NITOoaqo!h_owS_2JNSaunrSx>	<wordnet_group_100031264>	rdfs:subClassOf	<wordnet_abstraction_100002137>	
<id_WfEVb8RnlI_owS_FfbqagkpvN>	<wordnet_abstraction_105854150>	rdfs:subClassOf	<wordnet_concept_105835747>	
<id_FfbqagkpvN_owS_4XgTvCY8O1>	<wordnet_concept_105835747>	rdfs:subClassOf	<wordnet_idea_105833840>	
<id_lvMRfNeK9A_owS_NZI9npZ7TP>	<wordnet_idea_105837850>	rdfs:subClassOf	<wordnet_opinion_105945642>	
<id_KElb8G!es7_owS_69IkTT4EHI>	<wordnet_opinion_106782019>	rdfs:subClassOf	<wordnet_message_106598915>	
<id_fZc6yJ00GC_owS_MmqHnL5iv0>	<wordnet_message_106253690>	rdfs:subClassOf	<wordnet_communication_100033020>	
<id_xQKNxHaXyE_owS_pYmHmR88x!>	<wordnet_communication_113792842>	rdfs:subClassOf	<wordnet_connection_113791389>	
<id_6?iMaSRh!1_owS_g!8uX1QiEz>	<wordnet_connection_113870805>	rdfs:subClassOf	<wordnet_shape_100027807>	
<id_fMq7LWavj6_owS_YbC3i??RRd>	<wordnet_shape_105064037>	rdfs:subClassOf	<wordnet_spatial_property_105062748>	
<id_YbC3i??RRd_owS_c9XwTdKcW1>	<wordnet_spatial_property_105062748>	rdfs:subClassOf	<wordnet_property_104916342>	
<id_yZ8wu5330g_owS_dHlcugaJVG>	<wordnet_property_113244109>	rdfs:subClassOf	<wordnet_possession_100032613>	
<id_vMizwbd84a_owS_MlPbjMCWqZ>	<wordnet_possession_114407795>	rdfs:subClassOf	<wordnet_enchantment_114407536>	
<id_OHPBzkHGKw_owS_73L994dxVd>	<wordnet_enchantment_105979454>	rdfs:subClassOf	<wordnet_sorcery_105978812>	
<id_73L994dxVd_owS_Qvdykk6Ptb>	<wordnet_sorcery_105978812>	rdfs:subClassOf	<wordnet_magic_105967977>	
<id_Qvdykk6Ptb_owS_M??3!IZ0f>	<wordnet_magic_105967977>	rdfs:subClassOf	<wordnet_supernaturalism_105952490>	
<id_M??3!IZ0f_owS_g62IB513WY>	<wordnet_supernaturalism_105952490>	rdfs:subClassOf	<wordnet_belief_105941423>	
<id_g62IB513WY_owS_Me?JlZH4Wl>	<wordnet_belief_105941423>	rdfs:subClassOf	<wordnet_content_105809192>	
<id_H6fQ4IIRXf_owS_VTHJwP5SQ5>	<wordnet_content_107955057>	rdfs:subClassOf	<wordnet_collection_107951464>	
<id_RuvcSqhVFP_owS_H740xjMau?>	<wordnet_collection_101014066>	rdfs:subClassOf	<wordnet_grouping_101012360>	
<id_H740xjMau?_owS_HClL4W5hIu>	<wordnet_grouping_101012360>	rdfs:subClassOf	<wordnet_activity_100407535>	
<id_9TWizG2VER_owS_n3UPMfviBL>	<wordnet_activity_114531203>	rdfs:subClassOf	<wordnet_capability_114530836>	
<id_T?EoRNRTSP_owS_A!l3Y70K1L>	<wordnet_capability_105623181>	rdfs:subClassOf	<wordnet_aptitude_105622456>	
<id_A!l3Y70K1L_owS_ogRfl?JwTU>	<wordnet_aptitude_105622456>	rdfs:subClassOf	<wordnet_ability_105616246>	
<id_w4VXlTS15x_owS_HKG!trEZSO>	<wordnet_ability_105200169>	rdfs:subClassOf	<wordnet_quality_104723816>	
<id_HKG!trEZSO_owS_6q7HMI2?2i>	<wordnet_quality_104723816>	rdfs:subClassOf	<wordnet_attribute_100024264>
<id_6q7HMI2?2i_owS_2JNSaunrSx>	<wordnet_attribute_100024264>	rdfs:subClassOf	<wordnet_abstraction_100002137>	

The Loop consists of:
* abstraction
* concept
* idea
* opinion
* message
* communication
* connection
* shape
* spatial property
* property
* possession
* enchantment
* sorcery
* magic
* supernaturalism
* belief
* content
* collection
* grouping
* activity
* capability
* aptitude
* ability
* quality
* attribute

After that 'attribute' is again a subclass of 'abstraction'.

**Comment by AlexanderRassier** [comment]
Example 2:
'apple'

<id_bINOb!Lh6U_owS_pDC7N4dTy2>	<wordnet_apple_107739125>	rdfs:subClassOf	<wordnet_pome_113138842>	
<id_pDC7N4dTy2_owS_zumLjgGYAw>	<wordnet_pome_113138842>	rdfs:subClassOf	<wordnet_fruit_113134947>	
<id_zumLjgGYAw_owS_sia75p8Cg9>	<wordnet_fruit_113134947>	rdfs:subClassOf	<wordnet_reproductive_structure_111675842>	
<id_sia75p8Cg9_owS_QT7Q0iE1Hv>	<wordnet_reproductive_structure_111675842>	rdfs:subClassOf	<wordnet_plant_organ_113087625>	
<id_QT7Q0iE1Hv_owS_3J!LVFaZIX>	<wordnet_plant_organ_113087625>	rdfs:subClassOf	<wordnet_plant_part_113086908>	
<id_3J!LVFaZIX_owS_g5Xmr9iGUP>	<wordnet_plant_part_113086908>	rdfs:subClassOf	<wordnet_natural_object_100019128>	
<id_g5Xmr9iGUP_owS_r9CiCKIlsX>	<wordnet_natural_object_100019128>	rdfs:subClassOf	<wordnet_whole_100003553>	
<id_r9CiCKIlsX_owS_ndcBt49hxq>	<wordnet_whole_100003553>	rdfs:subClassOf	<wordnet_object_100002684>	
<id_yNm2HQiOSx_owS_Me?JlZH4Wl>	<wordnet_object_105810948>	rdfs:subClassOf	<wordnet_content_105809192>	
<id_H6fQ4IIRXf_owS_VTHJwP5SQ5>	<wordnet_content_107955057>	rdfs:subClassOf	<wordnet_collection_107951464>	
<id_RuvcSqhVFP_owS_H740xjMau?>	<wordnet_collection_101014066>	rdfs:subClassOf	<wordnet_grouping_101012360>	
<id_H740xjMau?_owS_HClL4W5hIu>	<wordnet_grouping_101012360>	rdfs:subClassOf	<wordnet_activity_100407535>	
<id_9TWizG2VER_owS_n3UPMfviBL>	<wordnet_activity_114531203>	rdfs:subClassOf	<wordnet_capability_114530836>	
<id_T?EoRNRTSP_owS_A!l3Y70K1L>	<wordnet_capability_105623181>	rdfs:subClassOf	<wordnet_aptitude_105622456>	
<id_A!l3Y70K1L_owS_ogRfl?JwTU>	<wordnet_aptitude_105622456>	rdfs:subClassOf	<wordnet_ability_105616246>	
<id_w4VXlTS15x_owS_HKG!trEZSO>	<wordnet_ability_105200169>	rdfs:subClassOf	<wordnet_quality_104723816>	
<id_HKG!trEZSO_owS_6q7HMI2?2i>	<wordnet_quality_104723816>	rdfs:subClassOf	<wordnet_attribute_100024264>	
<id_6q7HMI2?2i_owS_2JNSaunrSx>	<wordnet_attribute_100024264>	rdfs:subClassOf	<wordnet_abstraction_100002137>	
<id_WfEVb8RnlI_owS_FfbqagkpvN>	<wordnet_abstraction_105854150>	rdfs:subClassOf	<wordnet_concept_105835747>	
<id_FfbqagkpvN_owS_4XgTvCY8O1>	<wordnet_concept_105835747>	rdfs:subClassOf	<wordnet_idea_105833840>	
<id_lvMRfNeK9A_owS_NZI9npZ7TP>	<wordnet_idea_105837850>	rdfs:subClassOf	<wordnet_opinion_105945642>	
<id_KElb8G!es7_owS_69IkTT4EHI>	<wordnet_opinion_106782019>	rdfs:subClassOf	<wordnet_message_106598915>	
<id_fZc6yJ00GC_owS_MmqHnL5iv0>	<wordnet_message_106253690>	rdfs:subClassOf	<wordnet_communication_100033020>	
<id_xQKNxHaXyE_owS_pYmHmR88x!>	<wordnet_communication_113792842>	rdfs:subClassOf	<wordnet_connection_113791389>	
<id_6?iMaSRh!1_owS_g!8uX1QiEz>	<wordnet_connection_113870805>	rdfs:subClassOf	<wordnet_shape_100027807>	
<id_fMq7LWavj6_owS_YbC3i??RRd>	<wordnet_shape_105064037>	rdfs:subClassOf	<wordnet_spatial_property_105062748>	
<id_YbC3i??RRd_owS_c9XwTdKcW1>	<wordnet_spatial_property_105062748>	rdfs:subClassOf	<wordnet_property_104916342>	
<id_yZ8wu5330g_owS_dHlcugaJVG>	<wordnet_property_113244109>	rdfs:subClassOf	<wordnet_possession_100032613>	
<id_vMizwbd84a_owS_MlPbjMCWqZ>	<wordnet_possession_114407795>	rdfs:subClassOf	<wordnet_enchantment_114407536>	
<id_OHPBzkHGKw_owS_73L994dxVd>	<wordnet_enchantment_105979454>	rdfs:subClassOf	<wordnet_sorcery_105978812>	
<id_73L994dxVd_owS_Qvdykk6Ptb>	<wordnet_sorcery_105978812>	rdfs:subClassOf	<wordnet_magic_105967977>	
<id_Qvdykk6Ptb_owS_M??3!IZ0f>	<wordnet_magic_105967977>	rdfs:subClassOf	<wordnet_supernaturalism_105952490>	
<id_M??3!IZ0f_owS_g62IB513WY>	<wordnet_supernaturalism_105952490>	rdfs:subClassOf	<wordnet_belief_105941423>
<id_g62IB513WY_owS_Me?JlZH4Wl>	<wordnet_belief_105941423>	rdfs:subClassOf	<wordnet_content_105809192>

**Comment by thomasrebele** [comment]
Hello,
it seems to me that the path is not closed

In both examples you go from 
```
<wordnet_aptitude_105622456> rdfs:subClassOf <wordnet_ability_105616246>
<wordnet_ability_105200169> rdfs:subClassOf <wordnet_quality_104723816>
```
but `<wordnet_ability_105616246>` and `<wordnet_ability_105200169>` are two different entities.
(Wordnet uses synset ids to distinguish the different meanings of a word)

**Comment by AlexanderRassier** [comment]
You are right, that was something I did not pay attention to, sorry for that.

Thank you for the clarification and the fast response!
