### ISSUE TITLE
yago sparql endpoint

### ISSUE THREAD

**Issue by Faith1993** [yago-naga/yago3#5]
I am a college student form China. Recently, I want to obtain data using the YAGO SPARQL ENDPOINT, but I found  the url has not been open up. 

url:https://linkeddata1.calcul.u-psud.fr/sparql

Thank you!

**Comment by thomasrebele** [comment]
sorry for the late reply. The SPARQL endpoint should work again

**Comment by Faith1993** [comment]
thank you.

**Comment by trypuz** [comment]
The SPARQL endpoint does not work again.

**Comment by thomasrebele** [comment]
Sorry for the inconvenience, the endpoint is up again

**Comment by sdi1200144** [comment]
Hello,  I am a university student . I want to obtain data using the YAGO PARQL endpoint, but I found the url does not seem to work (https://linkeddata1.calcul.u-psud.fr/sparql) .
Thank you!

**Comment by thomasrebele** [comment]
Thanks for using YAGO! Unfortunately the endpoint is managed by a different team. We are in touch with the endpoint team and hope that the problem gets fixed soon.

**Comment by reckart** [comment]
Does the other team have an issue tracker as well that one can subscribe to to get notified when the service is back again?

**Comment by thomasrebele** [comment]
The SPARQL endpoint seems to be running again.

**Comment by quanchuynh** [comment]
The endpoint is again unavailable.

**Comment by ycallen** [comment]
Hi,
The endpoint has been unavailable for a while.

**Comment by mrviterbi** [comment]
Sparql endpoint is still unavailable.

**Comment by alinageorgiana97** [comment]
Sparql endpoint is still unavailable.

**Comment by Tpt** [comment]
Hi! We have released a new version of Yago, Yago 4. [It has a working sparql endpoint.](https://yago-knowledge.org/sparql).
However data and schema are very different from Yago 3. See [here](https://yago-knowledge.org/downloads/yago-4) for a description of Yago 4.
